### ISSUE TITLE
Other SCRAM passwords

### ISSUE THREAD

**Issue by Neustradamus** [tv42/scram-password#1]
Hello @tv42,

Thanks for your work on SCRAM!

Why do you not rename your repository:
- scram-sha-256-password

And create others like:
- scram-sha-1-password
- scram-sha-512-password
- scram-sha3-512-password

Or have one for all?

Some people uses other hashes too.

**Comment by tv42** [comment]
SCRAM-SHA-512 and SCRAM-SHA3-512 are not specified: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml#scram

SCRAM-SHA-512 etc also have no reason to exist; SHA256 is plenty strong for the use, and if it isn't then you need a *real* passphrase storage solution, with memory-hardness etc.

Nobody should be using SHA-1 for anything new, and I haven't encountered any software that uses SCRAM-SHA-1 so I haven't programmed it.

This repository is just a little command-line wrapper over https://github.com/xdg-go/scram
